### ISSUE TITLE
Question on RStudio development

### ISSUE THREAD

**Issue by dhdl** [kevinushey/blog#3]
Hi kevin,

since I've found no mail address from you, I'm misusing github now. Sorry!

How long will RStudio still rely on qt5-webkit?

Cheers,
Jacob

**Comment by kevinushey** [comment]
Hi Jacob,

We plan to stick with Qt WebKit for our desktop products for the foreseeable future. However, there are plans to revive development on Qt WebKit with the newer versions of Qt; we're hopeful that in v1.2 we'll be able to take advantage of those updates.

Thanks,
Kevin
